# Generated by Django 4.0.6 on 2022-07-23 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0003_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designation',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designation_employee', to='pay.designation'),
        ),
    ]
