# Generated by Django 4.0.6 on 2022-07-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0005_workingdays_alter_attendance_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workingdays',
            name='totalWorking',
        ),
        migrations.AddField(
            model_name='workingdays',
            name='daysInMonth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workingdays',
            name='paidOff',
            field=models.IntegerField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='workingdays',
            name='workDaysInMonth',
            field=models.IntegerField(choices=[(19, '19'), (20, '20'), (21, '21'), (22, '22')], default=20),
        ),
        migrations.AlterField(
            model_name='workingdays',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1),
        ),
        migrations.AlterField(
            model_name='workingdays',
            name='year',
            field=models.IntegerField(choices=[(2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025')], default=2022),
        ),
    ]
