# Generated by Django 4.0.6 on 2022-07-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0006_remove_workingdays_totalworking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingdays',
            name='paidOff',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
