# Generated by Django 4.0.6 on 2022-07-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0007_alter_workingdays_paidoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='actualWorkingDays',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
