# Generated by Django 4.0.6 on 2022-07-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0010_alter_attendance_actualworkingdays_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='actualWorkingDays',
        ),
        migrations.AddField(
            model_name='attendance',
            name='actualWorkDays',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
    ]
