# Generated by Django 4.0.6 on 2022-07-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0011_remove_attendance_actualworkingdays_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='actualWorkDays',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
