# Generated by Django 4.0.6 on 2022-07-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0013_employee_allowances_employee_conveyanceallowances_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='totalSalaryDay',
        ),
        migrations.AddField(
            model_name='salary',
            name='totalSalaryDays',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
