# Generated by Django 4.0.6 on 2022-07-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0014_remove_salary_totalsalaryday_salary_totalsalarydays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='totalSalaryDays',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
