# Generated by Django 4.0.6 on 2022-07-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0015_alter_salary_totalsalarydays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='totalSalaryDays',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
