# Generated by Django 4.0.6 on 2022-07-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0016_alter_salary_totalsalarydays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='totalSalaryDays',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
