# Generated by Django 4.0.6 on 2022-07-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0018_alter_salary_totalsalarydays'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='grossSalary',
            field=models.IntegerField(null=True),
        ),
    ]
