# Generated by Django 4.0.6 on 2022-07-31 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0020_salary_perdaysalary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='perDaySalary',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
    ]
