# Generated by Django 4.0.6 on 2022-07-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0021_alter_salary_perdaysalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='Total_Salary',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
    ]
