# Generated by Django 4.0.6 on 2022-07-31 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0022_salary_total_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='Total_Salary',
            new_name='totalSalary',
        ),
    ]
