# Generated by Django 4.0.6 on 2022-08-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0023_rename_total_salary_salary_totalsalary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
        migrations.AlterField(
            model_name='salary',
            name='perDaySalary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='totalSalary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
