# Generated by Django 4.1 on 2022-08-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0024_remove_attendance_date_alter_salary_perdaysalary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emailAddress',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='grossSalary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
