# Generated by Django 4.1 on 2022-08-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0025_employee_emailaddress_alter_employee_grosssalary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emailAddress',
        ),
        migrations.AddField(
            model_name='employee',
            name='account_Number',
            field=models.TextField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_Name',
            field=models.TextField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='email_Address',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
