# Generated by Django 4.1 on 2022-08-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0026_remove_employee_emailaddress_employee_account_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='lasstname',
            new_name='last_Name',
        ),
        migrations.AlterField(
            model_name='employee',
            name='account_Number',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_Name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
