# Generated by Django 4.1 on 2022-08-10 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0028_rename_firstname_employee_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='conveyanceAllowances',
            new_name='conveyance_Allowances',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='houseRentAllowance',
            new_name='house_Rent_Allowance',
        ),
    ]
