# Generated by Django 4.1 on 2022-08-10 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0029_rename_conveyanceallowances_employee_conveyance_allowances_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='grossSalary',
            new_name='gross_Salary',
        ),
    ]
