# Generated by Django 4.1 on 2022-08-10 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0030_rename_grosssalary_employee_gross_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='actualWorkDays',
            new_name='actual_Work_Days',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='loginTime',
            new_name='login_Time',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='logoutTime',
            new_name='logout_Time',
        ),
    ]
