# Generated by Django 4.1 on 2022-08-10 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0031_rename_actualworkdays_attendance_actual_work_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workingdays',
            old_name='daysInMonth',
            new_name='days_In_Month',
        ),
        migrations.RenameField(
            model_name='workingdays',
            old_name='workDaysInMonth',
            new_name='work_Days_In_Month',
        ),
    ]
