# Generated by Django 4.1 on 2022-08-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0035_employee_contact_number_employee_pan_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pAN_Number',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
    ]
