# Generated by Django 4.1 on 2022-08-10 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0036_alter_employee_pan_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designation',
            old_name='baseSalary',
            new_name='basic_Salary',
        ),
    ]
