# Generated by Django 4.1 on 2022-08-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0037_rename_basesalary_designation_basic_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='account_Number',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
