# Generated by Django 4.1 on 2022-08-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0038_alter_employee_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='provident_Fund',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
