# Generated by Django 4.1 on 2022-08-12 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0039_employee_provident_fund'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1)),
                ('year', models.IntegerField(choices=[(2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025')], default=2022)),
                ('work_Days_In_Month', models.IntegerField(choices=[(19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23')], default=20)),
                ('days_In_Month', models.IntegerField(blank=True, null=True)),
                ('paidOff', models.IntegerField(blank=True, null=True)),
            ],
            bases=(models.Model, object),
        ),
        migrations.AlterField(
            model_name='salary',
            name='workingDay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_workingDay', to='pay.workingmonth'),
        ),
        migrations.DeleteModel(
            name='WorkingDay',
        ),
    ]
