# Generated by Django 4.1 on 2022-08-12 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0040_workingmonth_alter_salary_workingday_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkingMonth',
            new_name='WorkingDay',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='allowances',
            new_name='other_Allowances',
        ),
    ]
