# Generated by Django 4.1 on 2022-08-12 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0041_rename_workingmonth_workingday_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='other_Allowances',
            new_name='allowances',
        ),
    ]
