# Generated by Django 4.1 on 2022-08-12 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0042_rename_other_allowances_employee_allowances'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkingDay',
            new_name='WorkingMonth',
        ),
    ]
