# Generated by Django 4.1 on 2022-09-02 08:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0044_alter_workingmonth_month_alter_workingmonth_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='account_Number',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contact_Number',
            field=models.PositiveIntegerField(null=True, unique=True, validators=[django.core.validators.RegexValidator('^[789]\\d{9}$', 'Enter Valid Number')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pAN_Number',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{5}[0-9]{4}[A-Z]{1}$', 'Enter Valid Pan Number')]),
        ),
    ]
